### ISSUE TITLE
dockerFlavorSync: command error

### ISSUE THREAD

**Issue by ioannist** [pidiscovery/pi#9]
Hi guys. I have been running Pi on a Windows Server 2019 bare metal machine with 1Gbs connection. I have passed docker and port tests and the stellar dummy image is up and running in Docker engine v20.10.5.

However, there seems to be a problem with the Consensus image as indicated by the log files.

Pi Node version number: 0.4.3
Consensus container enabled: No
Node switch on: Yes
PortsChecker container: running
Consensus container: absent
Operating system: WINDOWS 10.0.17763 (Microsoft Windows Server 2019 Standard)
Using Docker Toolbox: No
Node installation date: N/A
Availability (up to 90 days): N/A

From main file (C:\Users\yourname\AppData\Roaming\Pi Network\logs)
```
[2021-03-18 07:12:47.088] [error] run: stats: drive.info(): err: Error: disk name invalid and / not found
    at C:\Users\Administrator\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\node-os-utils\lib\drive.js:62:17
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[2021-03-18 07:12:47.142] [error] dockerFlavorSync: command error:  Error: Command failed: docker-machine env default
'docker-machine' is not recognized as an internal or external command,
operable program or batch file.
```

From renderer file
```
[2021-03-16 16:08:02.630] [debug] HOMEPAGE RENDER FUNCTION:
[2021-03-16 16:08:02.637] [debug] portsCheckPassed:  null
[2021-03-16 16:08:02.646] [debug] daemonOK:  true
[2021-03-16 16:08:02.753] [debug] HOMEPAGE RENDER FUNCTION:
[2021-03-16 16:08:02.759] [debug] portsCheckPassed:  true
[2021-03-16 16:08:02.765] [debug] daemonOK:  true
[2021-03-16 16:08:02.771] [debug] containerFlavor not null
[2021-03-16 16:08:09.193] [debug] Renderer: interval happening...
[2021-03-16 16:08:31.139] [debug] Renderer: interval happening...
```

The server has been running for 3 days.

**Comment by theword3** [comment]
I have the same issue

**Comment by theword3** [comment]
[2021-04-25 07:36:51.906] [error] consensusContainerUninstall error: failed to remove non-exsistent consensus container
[2021-04-25 07:36:55.712] [error] run: stats: drive.info(): err: Error: disk name invalid and / not found
    at F:\Anatoly\AppData\Local\Programs\pi-network-desktop\resources\app.asar\node_modules\node-os-utils\lib\drive.js:62:17
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
[2021-04-25 07:36:55.742] [error] dockerFlavorSync: command error:  Error: Command failed: docker-machine env default
"docker-machine" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.

    at ChildProcess.exithandler (child_process.js:304:12)
    at ChildProcess.emit (events.js:223:5)
    at ChildProcess.EventEmitter.emit (domain.js:475:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
[2021-04-25 07:36:56.035] [info] run: heartbeat: OK
[2021-04-25 07:36:56.037] [info] run: heartbeat: update-check: started: local-docker-image:  pinetwork/pi-node-docker:latest  new-docker-image: pinetwork/pi-node-docker:latest
[2021-04-25 07:36:56.038] [info] run: heartbeat: update-check: done: either already up to date, or not allowed to update, or docker daemon / container is not running
[2021-04-25 07:36:56.303] [error] dockerContainerStatsCommand: error: Command failed: docker stats pi-consensus --no-stream
Error response from daemon: No such container: pi-consensus

[2021-04-25 07:36:56.311] [error] run: stats: dockerContainerStatsCommand: err: Command failed: docker stats pi-consensus --no-stream
Error response from daemon: No such container: pi-consensus

[2021-04-25 07:36:56.910] [info] handleTestnetReset: starting reset
[2021-04-25 07:36:56.913] [info] handleTestnetReset: uninstalling consensus
[2021-04-25 07:36:56.915] [error] consensusContainerUninstall error: failed to remove non-exsistent consensus container
[2021-04-25 07:37:01.915] [info] handleTestnetReset: starting reset
[2021-04-25 07:37:01.919] [info] handleTestnetReset: uninstalling consensus
[2021-04-25 07:37:01.924] [error] consensusContainerUninstall error: failed to remove non-exsistent consensus container
[2021-04-25 07:37:06.948] [info] handleTestnetReset: starting reset

...
[2021-04-25 07:38:42.084] [info] handleTestnetReset: uninstalling consensus
[2021-04-25 07:38:42.086] [error] consensusContainerUninstall error: failed to remove non-exsistent consensus container

**Comment by ChrisAB** [comment]
Have any of you fixed the issue? Feels like the app is no longer maintained as this does not work with newer versions of Docker. Any idea what version of docker is recommended?
